export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_MOVIE = 'FETCH_MOVIE'
export const DELETE_DIRECTOR = 'DELETE_DIRECTOR'
export const DELETE_SUCCESSFUL = 'DELETE_SUCCESSFUL'
export const ADD_DIRECTOR = 'ADD_DIRECTOR'
export const ADD_DIRECTOR_SUCCESS = 'ADD_DIRECTOR_SUCCESS'
export const UPDATE_DIRECTOR = 'UPDATE_DIRECTOR'
export const UPDATE_DIRECTOR_SUCCESSFUL = 'UPDATE_DIRECTOR_SUCCESSFUL'
export const GET_SINGLE_DIRECTOR = 'GET_SINGLE_DIRECTOR'
export const GET_SINGLE_DIRECTOR_SUCCESSFUL = 'GET_SINGLE_DIRECTOR_SUCCESSFUL'



// GET_SINGLE_DIRECTOR
// ADD_DIRECTOR
// DELETE_SUCCESSFUL